---

repos_apt:
  - "ppa:fossfreedom/indicator-sysmonitor"

libraries_apt:
  - indicator-sysmonitor

sysmonitor:
  service   :
    name      : "indicator-sysmonitor"
    desc      : "Indicator System Monitor"
    dir       : "/lib/systemd/system/"

