---

#################################################################

- name: "sysmonitor service | start"
  service:
    name    : "{{ wallpaper.service.name }}"
    enabled : yes
    state   : restarted
  tags:
    - "system-monitor"

#################################################################

