---

#################################################################

- name: "apt | add repository"
  when: not proxy
  with_items:
    - "{{ repos_apt }}"
  apt_repository:
    repo  : "{{ item }}"
    state : "present"
  notify: "application | start"
  tags:
    - "system-monitor"

- name: "apt | add repository"
  when: proxy
  become: yes
  become_user: "{{ primary_user.id }}"
  with_items:
    - "{{ repos_apt }}"
  shell: "sudo -E add-apt-repository {{ item }} -y"
  notify: "application | start"
  tags:
    - "system-monitor"

- name: "mkdir"
  with_items:
    - { d: "{{ sysmonitor.service.dir   }}"                              }
  file:
    path  : "{{ item.d }}"
    state : "directory"
    owner : "{{ item.u | default(root_user.id)  }}"
    group : "{{ item.u | default(root_user.id)  }}"
    mode  : "0755"
  tags:
    - "system-monitor"

#################################################################

- name: "apt | install"
  apt:
    name  : "{{ libraries_apt }}"
    state : "latest"
  notify: "application | start"
  tags:
    - "system-monitor"

#################################################################

- name: "copy | config"
  template:
    src   : "indicator-sysmonitor.json.j2"
    dest  : "{{ primary_user.home }}/.indicator-sysmonitor.json"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0644"
  tags:
    - "system-monitor"

#################################################################

- name: "copy | systemd service"
  template:
    src   : "{{ sysmonitor.service.name }}.service.j2"
    dest  : "{{ sysmonitor.service.dir }}{{ sysmonitor.service.name }}.service"
    owner : "{{ root_user.id }}"
    group : "{{ root_user.id }}"
    mode: "0755"
  notify: "sysmonitor service | start"
  tags:
    - "system-monitor"

#################################################################

- name: "service | start"
  service:
    name    : "{{ sysmonitor.service.name }}"
    enabled : yes
    state   : started
  tags:
    - "system-monitor"

#################################################################

