---

#################################################################

- name: "apt | install"
  apt:
    name  : "{{ libraries_apt }}"
    state : "latest"
  tags:
    - "vim"

#################################################################

- name: "copy | .vimrc"
  with_items:
    - "{{ all_users }}"
  template:
    src   : "vimrc.j2"
    dest  : "{{ item.home }}/.vimrc"
    owner : "{{ item.id }}"
    group : "{{ item.id }}"
    mode  : 0644
  tags:
    - "vim"

- name: "git | pull vundle"
  with_items:
    - "{{ all_users }}"
  git:
    repo  : "http://github.com/gmarik/vundle.git"
    dest  : "{{ item.home }}/.vim/bundle/vundle"
    update: no
  tags:
    - "vim"

- name: "chmod | .vim"
  with_items:
    - "{{ all_users }}"
  file:
    dest    : "{{ item.home }}/.vim/"
    state   : directory
    recurse : yes
    owner   : "{{ item.id }}"
    group   : "{{ item.id }}"
    mode    : 0755
  tags:
    - "vim"

- name: "cmd | update plugins"
  with_items:
    - "{{ all_users }}"
  become: yes
  become_user: "{{ item.id }}"
  command: "vim -E -s -c 'source {{ item.home }}/.vimrc' -c PluginInstall -c qa"
  changed_when: False
  tags:
    - "vim"

#################################################################

- name: "copy | fonts"
  when: gui
  copy:
    src   : "PowerlineSymbols.otf"
    dest  : "/usr/local/share/fonts/"
    owner : "{{ root_user.id }}"
    group : "{{ root_user.id }}"
    mode  : 0644
  tags:
    - "vim"

- name: "copy | font config"
  when: gui
  with_items:
    - "{{ all_users }}"
  copy:
    src   : "10-powerline-symbols.conf"
    dest  : "{{ item.home }}/.config/fontconfig/fonts.conf/"
    owner : "{{ item.id }}"
    group : "{{ item.id }}"
    mode  : 0644
  tags:
    - vim

#################################################################

